---
- name: Install required packages
  apt:
    name={{ item }}
    state=present
  with_items:
    - nfs-common
    - apache2
    - libapache2-mod-php5
    - php5-gd
    - php5-mysql
    - php-cas
    - php5-ldap
    - python-mysqldb
    - git

- name: Wait for resources
  wait_for:
    host="{{ item.0 }}"
    port="{{ item.1 }}"
  with_together:
    - [ "{{ MySQL_VIRTUAL_IP }}", "{{ NFS_VIRTUAL_IP }}" ]
    - [ '3306', '111' ]

- name: Create drupal mysql database
  mysql_db:
    login_host="{{ MySQL_VIRTUAL_IP }}"
    login_user=root
    login_password=""
    name=forgeweb
    encoding=utf8
  when: "primary is defined"

- name: Create drupal mysql user
  mysql_user:
    login_host="{{ MySQL_VIRTUAL_IP }}"
    login_user=root
    login_password=""
    name=drupalcore
    password=drupalpass
    host="{{ ROUTER_PUBLIC_IP if IS_TARGET_OPENSTACK else ansible_default_ipv4.address }}"
    priv='forgeweb.*:SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES'
  when: "primary is defined"

- name: Enable Apache modules
  shell: a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - ssl

- name: Temporarily stop Apache for local configuration
  service:
    name=apache2
    state=stopped
  notify: restart apache

- name: remount the NFS share in case it hass been corrupted by previous configuration
  mount:
    name=/var/www
    src="{{ NFS_VIRTUAL_IP }}:/data/export"
    fstype=nfs
    opts="rw,vers=3"
    state={{ item }}
  notify: restart apache
  with_items:
    - unmounted
    - mounted

- name: Create tls directory for apache
  file:
    path=/etc/apache2/{{ certificate_path }}
    state=directory

- name: Upload ssl files
  copy:
    src={{ certificate_prefix }}.{{ item.0 }}
    dest=/etc/apache2/{{ certificate_path }}/{{ certificate_prefix }}.{{ item.0 }}
    owner=root
    group=root
    mode={{ item.1 }}
  notify: restart apache
  with_together:
    - [ crt, chain.pem, key ]
    - [ '0644', '0644', '0600' ]

- name: Configure Apache
  template:
    src=apache.j2
    dest=/etc/apache2/sites-available/default
    owner=root
    group=root
    mode=0644
  notify: restart apache

#- name: Check whether drupal is already installed
#  stat:
#    path=/var/www/index.php
#  register: drupal

- name: Get drupal
  git:
    repo=https://git.forgeservicelab.fi/druid/web.git
    dest=/var/www
    force=no
  when: "primary is defined"
  tags:
    - redeploy

- name: Ensure drupal ownership
  file:
    path=/var/www
    owner=www-data
    group=www-data
    recurse=yes
    state=directory
  when: "primary is defined"
  tags:
    - redeploy

#  shell: wget https://git.forgeservicelab.fi/druid/web/repository/archive -O drupal.tar.gz
#    chdir=/tmp
#    creates=/tmp/drupal.tar.gz
#  when: "primary is defined and not drupal.stat.exists"

#- name: Unpack drupal
#  shell: tar xzf drupal.tar.gz
#    chdir=/tmp
#    creates=/tmp/web.git
#  when: "primary is defined and not drupal.stat.exists"

#- name: Move drupal to webserver root
#  shell: mv web.git/* /var/www/
#    chdir=/tmp
#  when: "primary is defined and not drupal.stat.exists"
#  notify: restart apache

#- name: Move .htaccess
#  shell: mv web.git/.htaccess /var/www/
#    chdir=/tmp
#  when: "primary is defined and not drupal.stat.exists"
#  notify: restart apache

#- name: Move .gitignore
#  shell: mv web.git/.gitignore /var/www/
#    chdir=/tmp
#  ignore_errors: yes
#  when: "primary is defined and not drupal.stat.exists"
#  notify: restart apache

#- name: Check whether the modules are already installed
#  stat:
#    path=/var/www/sites/all/modules/{{ item.name }}
#  register: result
#  with_items:
#    - "{{ modules }}"

#- name: Get required modules
#  shell: wget http://ftp.drupal.org/files/projects/{{ item.item.name }}-{{ item.item.version }}.tar.gz
#    chdir=/tmp
#    creates=/tmp/{{ item.item.name }}-{{ item.item.version }}.tar.gz
#  with_items:
#    - "{{ result.results }}"
#  when: "primary is defined and not {{ item.stat.exists }}"

#- name: Unpack required modules
#  shell: tar xzf /tmp/{{ item.item.name }}-{{ item.item.version }}.tar.gz
#    chdir=/var/www/sites/all/modules
#    creates=/var/www/sites/all/modules/{{ item.item.name }}
#  with_items:
#    - "{{ result.results }}"
#  when: "primary is defined and not {{ item.stat.exists }}"
